name: Build JUCE VST Plugin

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake build-essential

      - name: Build plugin
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Upload plugin
        uses: actions/upload-artifact@v3
        with:
          name: JUCEVSTTemplate
          path: build/